language: python
python:
  - 2.7
  - 3.3
install:
  - python setup.py -q install
  - pip install -r requirements/travis.pip --use-mirrors
  - npm install -g bower
  - fab update_js
script:
  - fab coverage pep8
after_success:
  - coveralls -c coverage.rc
matrix:
  allow_failures:
    - python: 3.3
